sudo: requied 
services:
  - docker

before_install:
  - docker build -t junhanng11/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true junhanng11/react-test npm test

after_success:
  - docker build -t junhanng11/multi-client ./ client
  - docker build -t junhanng11/multi-nginx ./nginx
  - docker build -t junhanng11/multi-server ./server
  - docker build -t junhanng11/multi-worker ./worker
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push junhanng11/multi-client
  - docker push junhanng11/multi-nginx
  - docker push junhanng11/multi-server
  - docker push junhanng11/multi-worker